baseURL = 'https://vivianwilde.github.io/watchtower-blog/'
languageCode = 'en-us'
title = "Morgana's Watchtower Notes"
theme = 'm10c'
[params]
author = 'Morgan/a Ilkay'
description = 'Investigations into Time'
