baseURL = 'https://vivianwilde.github.io/watchtower-blog/'
languageCode = 'en-us'
title = "Morgana's Case Notes"
theme = 'm10c'
author = 'Morgan/a Ilkay'
[params]
author = 'Morgan/a Ilkay'
description = "Note: If you weren't actually at the session assume your character doesn't know anything here, it's just a way to organise notes OOC."


avatar = 'avatar.jpg'
[[menu.main]]
name = "Case Notes"
url = "/"
weight = 1
[[menu.main]]
name = "About"
title = "About"
url = "/about"
weight = 2

[pagination]
  # disableAliases = false
  pagerSize = 50
  path = 'page'
