baseURL = 'https://vivianwilde.github.io/watchtower-blog/'
languageCode = 'en-us'
title = "Morgana's Case Notes"
theme = 'm10c'
author = 'Morgan/a Ilkay'
[params]
author = 'Morgan/a Ilkay'
description = 'Unravelling the Mysteries of the Watchtower'
avatar = 'avatar.jpg'
[[menu.main]]
name = "Case Notes"
url = "/"
weight = 1
[[menu.main]]
name = "About"
title = "About"
url = "/about"
weight = 2
